import { C, card } from '../../theme';

export const ts = {
  section: {
    padding: '0 16px',
    marginBottom: 32,
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: 600,
    color: C.textMuted,
    letterSpacing: '0.10em',
    textTransform: 'uppercase',
    marginBottom: 12,
  },
  emptyText: {
    color: C.textSec,
    fontSize: 14,
    padding: '8px 0',
  },
  dayLabel: {
    fontSize: 12,
    fontWeight: 700,
    color: C.gold,
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
    padding: '10px 0 6px',
  },
  recordRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    padding: '14px 16px',
    background: C.surface2,
    border: `1px solid ${C.border}`,
    borderRadius: 12,
    marginBottom: 8,
    cursor: 'pointer',
    boxShadow: C.cardShadow,
    transition: 'border-color 0.15s',
  },
  recordRowActive: {
    borderColor: C.gold,
    background: C.goldDim,
  },
  recordTime: {
    fontSize: 15,
    fontWeight: 700,
    color: C.gold,
    minWidth: 42,
  },
  recordClient: {
    fontSize: 14,
    fontWeight: 600,
    color: C.text,
  },
  recordService: {
    fontSize: 12,
    color: C.textSec,
    marginTop: 2,
  },
  statsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(100px, 1fr))',
    gap: 10,
  },
  statCard: {
    ...card.stat,
  },
  statValue: {
    fontSize: 20,
    fontWeight: 800,
    color: C.gold,
    letterSpacing: '-0.02em',
  },
  statLabel: {
    fontSize: 11,
    color: C.textSec,
    marginTop: 4,
    letterSpacing: '0.04em',
  },
  periodRow: {
    display: 'flex',
    gap: 8,
    marginBottom: 14,
  },
  searchInput: {
    width: '100%',
    padding: '13px 14px',
    background: C.surface2,
    color: C.text,
    border: `1px solid ${C.border}`,
    borderRadius: 10,
    fontSize: 14,
    outline: 'none',
    boxSizing: 'border-box',
    boxShadow: C.inputShadow,
    transition: 'border-color 0.15s, box-shadow 0.15s',
  },
  searchResults: {
    background: C.surface2,
    border: `1px solid ${C.border}`,
    borderRadius: 12,
    marginTop: 4,
    overflow: 'hidden',
    boxShadow: C.cardShadow,
  },
  searchResultItem: {
    padding: '11px 14px',
    borderBottom: `1px solid ${C.border}`,
    cursor: 'pointer',
    transition: 'background 0.1s',
  },
  feedbackSelect: {
    width: '100%',
    padding: '12px 14px',
    background: C.surface2,
    color: C.text,
    border: `1px solid ${C.border}`,
    borderRadius: 10,
    fontSize: 14,
    marginBottom: 8,
    outline: 'none',
    boxShadow: C.inputShadow,
    transition: 'border-color 0.15s',
  },
  feedbackTextarea: {
    width: '100%',
    padding: '12px 14px',
    background: C.surface2,
    color: C.text,
    border: `1px solid ${C.border}`,
    borderRadius: 10,
    fontSize: 14,
    resize: 'vertical',
    outline: 'none',
    boxSizing: 'border-box',
    boxShadow: C.inputShadow,
    transition: 'border-color 0.15s',
  },
  feedbackItem: {
    padding: '12px 0',
    borderBottom: `1px solid ${C.border}`,
  },
  feedbackMeta: {
    fontSize: 12,
    color: C.textSec,
    marginBottom: 4,
  },
  noteItem: {
    padding: '12px 14px',
    borderRadius: 12,
    marginBottom: 8,
    background: C.surface2,
    border: `1px solid ${C.border}`,
    boxShadow: C.cardShadow,
  },
  noteImportant: {
    borderLeft: `3px solid ${C.gold}`,
  },
  noteMeta: {
    fontSize: 11,
    color: C.textSec,
    marginBottom: 4,
  },
};
