import { C, card } from '../../theme';

export const ms = {
  section: {
    padding: '0 16px',
    marginBottom: 32,
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: 600,
    color: C.textMuted,
    letterSpacing: '0.10em',
    textTransform: 'uppercase',
    marginBottom: 12,
  },
  statsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, 1fr)',
    gap: 10,
  },
  statCard: {
    ...card.stat,
  },
  statValue: {
    fontSize: 20,
    fontWeight: 800,
    color: C.gold,
    letterSpacing: '-0.02em',
  },
  statLabel: {
    fontSize: 11,
    color: C.textSec,
    marginTop: 4,
    letterSpacing: '0.04em',
  },
  periodRow: {
    display: 'flex',
    gap: 8,
    marginBottom: 14,
    flexWrap: 'nowrap',
    overflowX: 'auto',
    WebkitOverflowScrolling: 'touch',
    scrollbarWidth: 'none',
    msOverflowStyle: 'none',
  },
  subNav: {
    display: 'flex',
    gap: 8,
    padding: '0 16px',
    marginBottom: 16,
    overflowX: 'auto',
    scrollbarWidth: 'none',
  },
  tableRow: {
    display: 'flex',
    justifyContent: 'space-between',
    padding: '10px 0',
    borderBottom: `1px solid ${C.border}`,
    fontSize: 13,
  },
  tableHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    padding: '8px 0',
    borderBottom: `1px solid ${C.borderLight}`,
    fontSize: 11,
    color: C.textMuted,
    fontWeight: 600,
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
  },
  alertCard: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '12px 14px',
    background: C.surface2,
    border: `1px solid ${C.border}`,
    borderRadius: 12,
    marginBottom: 8,
    cursor: 'pointer',
  },
  alertBadge: {
    minWidth: 24,
    height: 24,
    borderRadius: 12,
    background: C.goldDim,
    border: `1px solid ${C.goldBorder}`,
    color: C.gold,
    fontSize: 12,
    fontWeight: 700,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '0 6px',
  },
  emptyText: {
    color: C.textSec,
    fontSize: 14,
    padding: '8px 0',
  },
  listItem: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    padding: '14px 16px',
    background: C.surface2,
    border: `1px solid ${C.border}`,
    borderRadius: 12,
    marginBottom: 8,
    cursor: 'pointer',
  },
  listIcon: {
    width: 36,
    height: 36,
    borderRadius: 10,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    color: C.gold,
    background: 'rgba(0,229,204,0.08)',
  },
  listLabel: {
    fontSize: 15,
    fontWeight: 600,
    color: C.text,
  },
  listDesc: {
    fontSize: 12,
    color: C.textSec,
    marginTop: 2,
  },
};
