import { C, btn, card } from '../../theme';

export const cs = {
  section: {
    padding: '0 16px',
    marginBottom: 28,
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: 600,
    color: C.textMuted,
    letterSpacing: '0.10em',
    textTransform: 'uppercase',
    marginBottom: 12,
  },
  emptyText: {
    color: C.textSec,
    fontSize: 14,
    padding: '16px 0',
  },
  recordItem: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '14px 16px',
    background: C.surface2,
    border: `1px solid ${C.border}`,
    borderRadius: 12,
    marginBottom: 8,
    boxShadow: C.cardShadow,
    transition: 'border-color 0.15s',
  },
  recordDate: {
    fontSize: 13,
    color: C.textSec,
    marginTop: 3,
  },
  recordService: {
    fontSize: 15,
    fontWeight: 600,
    color: C.text,
  },
  successBanner: {
    margin: '0 16px 20px',
    padding: '16px',
    background: C.goldDim,
    border: `1px solid ${C.goldBorder}`,
    borderRadius: 12,
    boxShadow: C.glow,
  },
  successTitle: {
    fontSize: 14,
    fontWeight: 700,
    color: C.gold,
    marginBottom: 4,
  },
  successText: {
    fontSize: 13,
    color: C.textSec,
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: '50%',
    background: C.gold,
    boxShadow: '0 0 8px rgba(0,229,204,0.4)',
  },
  cancelBtn: {
    background: 'none',
    border: `1px solid ${C.error}`,
    color: C.error,
    fontSize: 12,
    fontWeight: 600,
    borderRadius: 8,
    padding: '5px 10px',
    cursor: 'pointer',
  },
  overlay: {
    position: 'fixed',
    top: 0, left: 0, right: 0, bottom: 0,
    background: 'rgba(0,0,0,0.7)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
    padding: 16,
  },
  dialog: {
    background: C.surface,
    border: `1px solid ${C.border}`,
    borderRadius: 16,
    padding: 24,
    maxWidth: 340,
    width: '100%',
    textAlign: 'center',
  },
  dialogTitle: {
    fontSize: 16,
    fontWeight: 700,
    color: C.text,
    marginBottom: 8,
  },
  dialogText: {
    fontSize: 14,
    color: C.textSec,
    marginBottom: 20,
  },
  dialogActions: {
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
  },
  rebookBtn: {
    ...btn.ghost,
    color: C.gold,
    fontSize: 13,
  },
  historyItem: {
    padding: '12px 16px',
    background: C.surface2,
    border: `1px solid ${C.border}`,
    borderRadius: 12,
    marginBottom: 8,
  },
  historyRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  historyService: {
    fontSize: 14,
    fontWeight: 600,
    color: C.text,
  },
  historyPrice: {
    fontSize: 14,
    fontWeight: 600,
    color: C.gold,
  },
  historyMeta: {
    fontSize: 12,
    color: C.textSec,
    marginTop: 4,
  },
  profilePageTitle: {
    fontSize: 16,
    fontWeight: 700,
    color: C.text,
    marginBottom: 14,
  },
};
